### PR TITLE
fix(footer): move landmark role to host

### LINKED ISSUE #2686: [bug] `<rh-footer>` not being exposed as a page landmark
**Edit: looks like this is being caused by RHDC lazy loading the footer upon scroll.**

[Here's why we still may want to address it.](https://github.com/RedHat-UX/red-hat-design-system/issues/2686#issuecomment-3429544807)

The following is what I thought was happening, initially:

------

Pages at redhat.com currently have no footer (aka contentInfo) landmark upon load. Screen reader users attempting to navigate the page via landmarks can only access the navigation and main landmarks--not the footer.

`<rh-footer>` currently has no role. Instead, it contains a `<footer>` (and its implicit contentInfo role) within it. ([Relevant source here](https://github.com/RedHat-UX/red-hat-design-system/blob/bbb5b3c37418620c0ce40fe5bb9462f804ef7ec6/elements/rh-footer/rh-footer.ts#L71))

@adamjohnson suggested we may want to set `role="contentInfo"` on `<rh-footer>` and remove the `<footer>` element from the shadow DOM. I'm not sure what knock-on effects this will have for styles, if any.

If you want to verify this issue for yourself, you can do so at redhat.com.

1. On a Mac, turn on VoiceOver.
2. Go to www.redhat.com in your browser (Safari preferred, but any will work).
3. Open the Rotor with `control-option-u`, and press the arrow keys until you see the page landmarks.
4. You will _not_ see a footer landmark listed.

VoiceOver screenshot of redhat.com showing no footer landmark

_h/t Jairus Mitchell for asking about footers at RHDC and getting this discussion started._

### PR DESCRIPTION
**Pull request by adamjohnson**
## What I did

1. Fixes #2686 
2. Removed `<footer>` elements from `<rh-footer>` and `<rh-footer-univeral>`'s shadowdom.
3. Using InternalsController to apply the [`contentinfo` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/contentinfo_role) to each of the above's host elements.
4. `<rh-footer-universal>` only gets the contentinfo role IF it's not contained in a parent `<footer>` or `<rh-footer>` element.

## Testing Instructions

1. Open [the DP](https://deploy-preview-2722--red-hat-design-system.netlify.app/elements/footer/).
2. Verify no `<footer>` elements exist in the shadowdom of `<rh-footer>` and `<rh-footer-universal>`.
3. On the [`<rh-footer>` demo](https://deploy-preview-2722--red-hat-design-system.netlify.app/elements/footer/demo/), verify that `<rh-footer>` has the `contentinfo` role via the a11y tree.
4. Then, on the same demo, verify that `<rh-footer-universal>` does NOT have the `contentinfo` role.
5. Now move to the [`<rh-footer-universal>` demo in the DP](https://deploy-preview-2722--red-hat-design-system.netlify.app/elements/footer/demo/footer-universal/).
6. Verify that `<rh-footer-universal>` DOES have the `contentinfo` role since it's not wrapped by a `<footer>` or `<rh-footer>` element.
7. Ensure rh-footer remains in spec for design.
8. Ensure there are no axe/lighthouse errors that shouldn't be there.
9. Check the formatting of the changeset (do we usually put sub-components in there?)

### CODE REVIEW

**Review by hellogreg — APPROVED** [review]
landmark gets total makeover

File: elements/rh-footer/rh-footer-universal.ts [hunk 1]
```diff
@@ -31,26 +33,59 @@ export class RhFooterUniversal extends LitElement {
...
+        break;
+      }
+
+      node = node.parentElement;
+    }
+
+    if (!hasFooterAncestor) {
+      this.#internals.role = 'contentinfo';
+    }
+  }
```
Comment (zeroedin) [inline elements/rh-footer/rh-footer-universal.ts:108]: We should use @lit/context here instead of doing this parentElement check.

**Comment by bennypowers** [comment]
I generally approve and im sure @paceaux will too

Just want to make sure we aren't breaking backwards

File: elements/rh-footer/rh-footer-universal.ts (hunk 1 above)
Comment (zeroedin) [reply elements/rh-footer/rh-footer-universal.ts:108]: @bennypowers thoughts on this? I went ahead and mocked up the changes locally if we want to use @lit/context. If not I can revert and resolve the comment.

Comment (bennypowers) [reply elements/rh-footer/rh-footer-universal.ts:108]: This is to avoid breaking backwards, right?

It's not going to be so easy for us to set every native footer as a context host on the page.

You could potentially conceive of a situation where there's like a custom footer element that uses element internals that we'd have to watch out for.

But I think maybe for most of our cases this is going to be plenty, although maybe we should leave a comment here that explains the limitations of the approach. as well as some documentation on the website.

Comment (zeroedin) [reply elements/rh-footer/rh-footer-universal.ts:108]: Ok yes I follow.  

the lit context would only work in `<rh-footer><rh-footer-universal>` pairing.  Not `<footer><rh-footer-universal>`.    I'll resolve and revert my changes locally. Didn't think of that scenario.
