### PR TITLE
fix(footer)!: rename global-footer to footer-universal

### LINKED ISSUE #785: [feat] <rh-footer-universal>
### Description

Rename (with fallback) `<rh-global-footer>` to `<rh-footer-universal>`.

### Suggested solution

 See #746 

### Example API

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #785 

## What I did

1. Rename `<rh-global-footer>` to `<rh-footer-universal>`
1. Alias `<rh-footer-universal>` to `<rh-global-footer>`
2. Update docs, demos, and examples

## Testing Instructions

1. Check that the rh-footer-universal demo works as expected
1. Run spandx and check that the `<rh-global-footer>` alias still works

### CODE REVIEW

File: elements/rh-footer/rh-global-footer.ts
Comment (zeroedin) [inline elements/rh-footer/rh-global-footer.ts:1]: This is what I should have done with the secondary nav instead of renaming the file and declaring the old tag/deprecation in the new file name.

File: elements/rh-footer/docs/20-guidelines.md [hunk 1]
```diff
@@ -39,25 +39,25 @@ websites.
...
-| Default           | Call to action            | `--rh-color-interactive-blue-lighter`                |
-| Default           | Red Hat fedora icon       | `--rh-color-black-500`                               |
-| Default           | Global nav and legal link | `--rh-color-white`                                   |
+| Interaction State | Element                    | Text Styling                                         |
+| ----------------- | -------------------------- | ---------------------------------------------------- |
+| Default           | Social media link          | `--rh-color-black-500`                               |
+| Default           | Modular nav link           | `--rh-color-white`                                   |
+| Default           | Call to action             | `--rh-color-interactive-blue-lighter`                |
+| Default           | Red Hat fedora icon        | `--rh-color-black-500`                               |
+| Default           | Universal & and legal link | `--rh-color-white`                                   |
```
Comment (heyMP) [inline elements/rh-footer/docs/20-guidelines.md:48]:
```suggestion
| Default           | Universal & legal link | `--rh-color-white`                                   |
```

**Review by heyMP — APPROVED** [review]
Thank you for this update! 🙏

**Comment by bennypowers** [comment]
the final countdown
