### PR TITLE
fix: theming for elements

### LINKED ISSUE #1852: Theming leftovers
If you think any of this feedback should be tackled in separate PRs, I'm good with merging #1792 into the staging branch.

**accordion:**
- [x] Background color of closed accordion header should be transparent. When open, its bg color should match the panel’s bg color.

**alert:**
- [x] Alert on dark is using white text. Maybe we have to add a token for situations like this, or should alert be a color context provider?

**audio player:**
- [x] Needs a `--rh-color-border-subtle-on-light` or `--rh-color-border-subtle-on-dark`
- [x] Needs a dark theme demo

**badge:**
- [x] The critical badge should be using a darker red orange color, and the important should also be using a red orange shade. I think this could be updated by adding status tokens to the other repo.

**blockquote:**
- [x] `border-inline-start` should be using `--rh-color-accent-brand-on-light` or `--rh-color-accent-brand-on-dark`

**button:**
- [ ] #1884
- [x] Disabled button on dark is using same colors as the on light version, but it should be different based on [Figma file](https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?node-id=9-521&m=dev).

**card:**
- [x] When I change the card’s color palette, it also changes the color palette of the rest of the demo. Is this a bug in the demo or expected behavior based on new theming rules?

**health index:**
- [x] Border colors for light and dark themes don’t look quite the same as [what we have in Figma](https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?node-id=2709-157&m=dev)

**stat:**
- [x] On dark, statistic and title slots should use `--rh-color-text-brand-on-dark`

**table:**
- [ ] #1885

**tabs:**
- [x] Links in tab panels aren’t showing correct colors in dark or light theme. I think this might be due to site styles messing with the demo.
- [ ] #1886

**tile:**
- [x] Footer slot and arrow are misaligned. (Not due to color context, but wanted to note it in case it's a demo-only bug and not an issue in the element.)

_Originally posted by @marionnegp in https://github.com/RedHat-UX/red-hat-design-system/pull/1792#pullrequestreview-2293718513_

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #1852

Blocked by #1845 

:point_right: **NOTE**: this PR leaves audio player alone. let's tackle that in a [follow up ](https://github.com/RedHat-UX/red-hat-design-system/pull/1854):point_left: 

## TODO

- [ ] **audio player:** see #1854 Needs a `--rh-color-border-subtle-on-light` or `--rh-color-border-subtle-on-dark`
- [ ] **audio player:** see #1854 Needs a dark theme demo
- [ ] **button:** Disabled button on light should be using `--rh-color-gray-50`, but there’s no semantic token for this. Should probably add disabled color tokens.
- [ ] **table:** `--rh-color-interactive-primary-default-on-dark` doesn’t have enough contrast with the bg color of the hover state.

### Accordion

It wasn't clear to me what the spec is here, so I did this: collapsed headers have no background. expanded headers and panels use either 
```css
.expanded.on.light {
  --rh-color-surface: var(--rh-color-surface-lightest, #ffffff);
}

.expanded.on.dark {
  --rh-color-surface: var(--rh-color-surface-darkest, #151515);
}
```

### Alert
I'd like alert to be more themable. right now it composes a surface which is always lightest, so i simply updated the css and template to work with the new theming tokens, but just always be on light.
status tokens are:
- danger
- warning
- caution
- neutral
- note
- success

then there are surface status tokens:
- surface-status-danger
- surface-status-warning
- surface-status-info
- surface-status-default
- surface-status-success

and icon tokens:
- icon-status-danger
- icon-status-warning
- icon-status-info
- icon-status-default
- icon-status-success

whereas alert states are:
- danger
- warning
- info
- success

and compounding the problem, border tokens are like:
- strong
- subtle
- interactive
- destructive

and even worse, the alert danger state doesn't use token values at all.

so that needs a bit of design thinking to align on names and states. perhaps we could use relative colour in oklch for the alert borders, rather than named tokens. in the mean time i'll just map info to note:

```css
#container.info {
  --_border-color: var(--rh-color-status-note);
  --_icon-color: var(--rh-color-icon-status-info);
  --_header-color: var(--rh-color-status-note);
  --_background-color: var(--rh-color-surface-status-info);
}

#container.success {
  --_border-color: var(--rh-color-status-success);
  --_icon-color: var(--rh-color-icon-status-success);
  --_header-color: var(--rh-color-status-success);
  --_background-color: var(--rh-color-surface-status-success);
}

#container.warning {
  --_border-color: var(--rh-color-status-warning);
  --_icon-color: var(--rh-color-icon-status-warning);
  --_header-color: var(--rh-color-status-warning);
  --_background-color: var(--rh-color-surface-status-warning);
}

#container.danger {
  --_border-color: var(--rh-color-status-danger);
  --_icon-color: var(--rh-color-icon-status-danger);
  --_header-color: var(--rh-color-status-danger);
  --_background-color: var(--rh-color-surface-status-danger);
}
```

### Badge
See above in Alert re state tokens. badge has states:
- info
- success
- moderate
- important
- critical
it's not clear how or if those map to status tokens. For now i kept them with the crayon tokens, but we could just as well use the theme status tokens

### Health Index
I set the borders to border-subtle. is that correct?

### Statistic
did i get this right? is the icon supposed to be brand color, always?

### Tabs
Doesn't look like there is a hover state spec'd in figma

### Tag
implemented changes from #1843 

### Tile
Fixed this by making the icon container 

## Testing Instructions

1.

### CODE REVIEW

**Review by zeroedin — COMMENTED** [review]
Various Issues noted during review, not necessarily directly associated with changes in this PR directly, but using this as a scratch pad to then move them off to separate issues where deemed necessary. 

- [ ] Accordion showing drop shadows on panel when expanded, also present in clefairy, so not directly specific to this PR.  Figma shows this drop shadow to exist on the whole accordion not the header/panels.  

This DP:
image

Clefairy:
image


ux.redhat.com
image

Figma
Screenshot 2024-09-13 at 2 10 35 PM

- [ ] Alert demo toast, mixture of `variant="toast"` and `toast` as boolean attr

File: elements/rh-blockquote/rh-blockquote.ts [hunk 1]
```diff
@@ -54,9 +54,9 @@ export class RhBlockquote extends LitElement {
   @property({ reflect: true }) size: 'default' | 'large' = 'default';
 
   render() {
-    const { on = '' } = this;
+    const { highlight, on = '' } = this;
     return html`
-      <figure id="container" class="${classMap({ [on]: !!on })}">
+      <figure id="container" class="${classMap({ highlight, [on]: !!on })}">
```
Comment (zeroedin) [inline elements/rh-blockquote/rh-blockquote.ts:59]: Doesn't seem to be loading the `on` class by default

https://deploy-preview-1853--red-hat-design-system.netlify.app/elements/blockquote/demo/

DP:
Screenshot 2024-09-13 at 2 38 05 PM

Expected:
Screenshot 2024-09-13 at 2 37 59 PM

File: elements/rh-tabs/demo/nested.html [hunk 2]
```diff
@@ -28,6 +28,19 @@
...
+    &:hover { color: var(--rh-color-interactive-primary-hover); }
+    &:focus-within { color: var(--rh-color-interactive-primary-focus); }
+    &:active { color: var(--rh-color-interactive-primary-active); }
+    &:visited {
+      color: var(--rh-color-interactive-primary-visited);
+      &:hover { color: var(--rh-color-interactive-primary-visited-hover); }
+      &:focus-within { color: var(--rh-color-interactive-primary-visited-focus); }
+      &:active { color: var(--rh-color-interactive-primary-visited-active); }
+    }
+  }
```
Comment (zeroedin) [inline elements/rh-tabs/demo/nested.html:43]: @bennypowers instead of adding these to the demo, could we add [base layer styles](https://github.com/RedHat-UX/red-hat-design-system/blob/c913b8fb9bb8f167d8704ceb67f383ceacb34672/docs/styles/styles.css#L26-L75) via the changes in https://github.com/RedHat-UX/red-hat-design-system/pull/1862 to [docs/styles/demo/styles.css](https://github.com/RedHat-UX/red-hat-design-system/pull/1862/files#diff-611152b35fc6b837bacde981148e7e8c227cb2f10f6ca037074df6ee66651c7a) for demos.  To me it only makes sense to remove these from the demo css as it really has nothing to do with the tabs demos themselves.

File: elements/rh-tag/demo/filled-color-with-icon.html [hunk 3]
```diff
@@ -1,10 +1,12 @@
...
-<rh-tag color="cyan" icon="information">Cyan</rh-tag>
-<rh-tag color="blue" icon="information">Blue</rh-tag>
-<rh-tag color="purple" icon="information">Purple <svg slot="icon" fill="currentColor" viewBox="0 0 512 512" aria-hidden="true" role="img"><path d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 110c23.196 0 42 18.804 42 42s-18.804 42-42 42-42-18.804-42-42 18.804-42 42-42zm56 254c0 6.627-5.373 12-12 12h-88c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h12v-64h-12c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h64c6.627 0 12 5.373 12 12v100h12c6.627 0 12 5.373 12 12v24z"></path></svg></rh-tag>
```
Comment (zeroedin) [inline elements/rh-tag/demo/filled-color-with-icon.html:6]: Are you removing this to bring less attention to the ability to slot a icon as well?  If not should this be broken out into another demo `slotted-icons.html`

File: elements/rh-tag/demo/outline-with-icon.html [hunk 4]
```diff
@@ -1,20 +1,10 @@
...
-  </svg>
-</rh-tag>
-<rh-tag color="cyan" variant="outline" icon="information">Cyan</rh-tag>
-<rh-tag color="blue" variant="outline" icon="information">Blue</rh-tag>
-<rh-tag color="purple" variant="outline" icon="information">
-  Purple
-  <svg slot="icon" height="1em" width: "1em" fill="currentColor" viewBox="0 0 512 512" aria-hidden="true" role="img">
-    <path d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 110c23.196 0 42 18.804 42 42s-18.804 42-42 42-42-18.804-42-42 18.804-42 42-42zm56 254c0 6.627-5.373 12-12 12h-88c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h12v-64h-12c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h64c6.627 0 12 5.373 12 12v100h12c6.627 0 12 5.373 12 12v24z"></path>
```
Comment (zeroedin) [inline elements/rh-tag/demo/outline-with-icon.html:14]: same as in tag, are we making the slot capability for icons less visible?

File: elements/rh-tag/rh-tag.css
Comment (zeroedin) [inline elements/rh-tag/rh-tag.css:1]: Tag styles don't seem to be loading in demo

image

File: elements/rh-tabs/demo/nested.html (hunk 2 above)
Comment (bennypowers) [reply elements/rh-tabs/demo/nested.html:43]: i dont' want there to be any dependencies on the demos except the global css at maximum

a user should be able to copy paste the entire demo into a fresh page and get the same results or near-to

File: elements/rh-tag/rh-tag.css
Comment (bennypowers) [reply elements/rh-tag/rh-tag.css:1]: #1845

File: elements/rh-tag/demo/outline-with-icon.html (hunk 4 above)
Comment (bennypowers) [reply elements/rh-tag/demo/outline-with-icon.html:14]: [c9c3b22](https://github.com/RedHat-UX/red-hat-design-system/pull/1853/commits/c9c3b2201964b16b79e6e0131a10a5bda6a4e76d)

File: elements/rh-tag/demo/filled-color-with-icon.html (hunk 3 above)
Comment (bennypowers) [reply elements/rh-tag/demo/filled-color-with-icon.html:6]: [c9c3b22](https://github.com/RedHat-UX/red-hat-design-system/pull/1853/commits/c9c3b2201964b16b79e6e0131a10a5bda6a4e76d)
